"""
Django settings for gnext project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-m+8s58hud9#cjl_bvnkg9q+91yby*nujl%c!8%0f7eq(nte&4#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',        # Removed - no admin interface needed
    # 'django.contrib.auth',          # Removed - no authentication needed
    # 'django.contrib.contenttypes',  # Removed - no database models
    # 'django.contrib.sessions',      # Removed - stateless API
    # 'django.contrib.messages',      # Removed - no user messages
    'django.contrib.staticfiles',
    'rest_framework',
    'django_extensions',
    'backend',
    'corsheaders'
]

REST_FRAMEWORK = {
    'URL_FORMAT_OVERRIDE': None,
    'DEFAULT_AUTHENTICATION_CLASSES': [],  # Disable authentication
    'DEFAULT_PERMISSION_CLASSES': [],      # Disable permissions
    'UNAUTHENTICATED_USER': None,          # Don't use auth models
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ✅ must be above CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',      # Removed - no sessions
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',                 # Removed - stateless API
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',   # Removed - no auth
    # 'django.contrib.messages.middleware.MessageMiddleware',      # Removed - no messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True # TODO: set to false in production
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'gnext.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',       # Removed - no auth
                # 'django.contrib.messages.context_processors.messages', # Removed - no messages
            ],
        },
    },
]

WSGI_APPLICATION = 'gnext.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Not using any database - all data is file-based (BGZ, LMDB) and Typesense

DATABASES = {
    # Dummy database config to keep Django happy
    'default': {
        'ENGINE': 'django.db.backends.dummy'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # where collectstatic will put files

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Typesense config
# Host defaults to localhost for development, Docker overrides via environment variables
TYPESENSE_CONFIG = {
    "nodes": [{
        "host": config("VITE_TYPESENSE_HOST", default="localhost"),
        "port": config("VITE_TYPESENSE_PORT"),
        "protocol": "http"
    }],
    "api_key": config("VITE_TYPESENSE_KEY"),
    "connection_timeout_seconds": 3600
}

# Configuration parameters
NF_DATA_DIR = config("NF_DATA_DIR")
NORM_DIR = os.path.join(NF_DATA_DIR, "normalize")
MANHATTAN_DIR = os.path.join(NF_DATA_DIR, "manhattan_qq")
QQ_DIR = os.path.join(NF_DATA_DIR, "manhattan_qq")
VEP_DIR = os.path.join(NF_DATA_DIR, "annotate")
VCF_FILE = os.path.join(VEP_DIR, "full_variants.vcf.gz")
ANNO_VCF_FILE = os.path.join(VEP_DIR, "out/annotated_full_variants.vcf.gz")
MAGMA_RESULTS_DIR = os.path.join(NF_DATA_DIR, "magma_results")
CHR_BGZ_DIR = os.path.join(NF_DATA_DIR, "chr_bgz")
LMDB_RSID_FILE = os.path.join(NF_DATA_DIR, "lmdb_rsid/lmdb-data.mdb")
LMDB_GENE_FILE = os.path.join(NF_DATA_DIR, "lmdb_gene/lmdb-data.mdb")
GENE_FILE = os.path.join(NF_DATA_DIR, "lmdb_gene/mapped_genes.tsv")
TOP_HITS_FILE = os.path.join(NF_DATA_DIR, "top_hits/top_hits.json")
NF_PARAM_FILE = os.path.join(NF_DATA_DIR, "meta/workflow_params.json")
GENE_MAGMA_BGZ_FILE = os.path.join(NF_DATA_DIR, "magma_results/gene_magma_pvalues.tsv.bgz")
GENE_MAGMA_INDEX_FILE = os.path.join(NF_DATA_DIR, "magma_results/lmdb-data.mdb")


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'django': {
            'format': '[%(asctime)s] %(levelname)s %(message)s',
            'datefmt': '%d/%b/%Y %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'backend': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': True,
        }
    },
}